shwestrick/smlfmt

- parse/Parser.sml
+ Problem: Currently, the program:
```sml
fun foo (x::xs) = x
```
is being rejected. See the following:
```
λ ~/P/parse-sml on fix-cons-patterns  ./main test/succeed/functions.sml                                                      16:44:23
fun foo (x::xs) = x
Parsing...
-- PARSE ERROR -------------------------------------- test/succeed/functions.sml
Infix identifier not prefaced by 'op'
1| fun foo (x::xs) = x
^^
```
This appears to be due to the `if` branch for pattern constructors coming before the branch for infix constructors. Infix constructors fall into the requirements for the first case, meaning that we never reach the infix branch. This leads to an error about infix identifiers, since now "op" is expected.
+ Solution: Swap the two branches. Seems that all the …
> Fix cons patterns

- parse/Parser.sml
- test/fail/bad-functions.sml
- test/succeed/functions.sml
+ Problem: We cannot currently parse multi-clause functions. For instance, consider the function:
```sml
fun fact 0 = 1
| fact n = n * fact (n-1)
```
Attempting to parse this program produces:
```
λ ~/P/parse-sml on main ◦ ./main test.sml                                                            17:41:48
fun fact 0 = 1
| fact n = n * fact (n-1)
Parsing...
-- PARSE ERROR -------------------------------------------------------- test.sml
Unexpected token.
2|   | fact n = n * fact (n-1)
^
Invalid start of top-level declaration!
```
+ Solution: We have added support for multi-clausal function definitions. Also, there is a check that the names of each clause in the function must be the same, and it will throw an error if it does not (with the expected name). There are some …
> Add function branches

- parse/Parser.sml
- test/succeed/mutually-recursive-types.sml
+ Problem: Currently, we cannot parse programs with mutually recursive types. Consider the program:
```sml
type 'a foo = int
and 'b bar = 'b option
and ('c, 'd) baz = 'c * 'd -> int list
```
This currently results in the following:
```
λ ~/P/parse-sml on main ◦ ./main test/succeed/mutually-recursive-types.sml
type 'a foo = int
and 'b bar = 'b option
and ('c, 'd) baz = 'c * 'd -> int list
Parsing...
-- PARSE ERROR --------- test/succeed/mutually-recursive-types.sml
Unexpected token.
2| and 'b bar = 'b option
^^^
Invalid start of top-level declaration!
```
+ Solution: Added in support for mutually recursive types. Now, we get:
```
λ ~/P/parse-sml on main ◦ ./main test/succeed/mutually-recursive-types.sml
type 'a foo = int
and 'b bar = 'b option
and ('c, 'd) baz = 'c * 'd …
```
> added support for mutually recursive types

- parse/Parser.sml
- parse/PrettyPrintAst.sml
- test/fail/bad-local-in-end-1.sml
- test/fail/bad-local-in-end-2.sml
- test/fail/bad-local-in-end-3.sml
- test/succeed/local-in-end.sml
+ Problem: Currently, there is no support for local declarations. Consider the following program:
```sml
local
val x = 2
in
val y = x
end
```
This will cause the following error when parsed:
```
λ ~/P/parse-sml on main ◦ cat test.sml                    18:58:12
local
val x = 2
in
val y = x
end
λ ~/P/parse-sml on main ◦ ./main test.sml                 18:58:14
local
val x = 2
in
val y = x
end
Parsing...
-- ERROR: NOT YET IMPLEMENTED --------------------------- test.sml
Unexpected token.
1| local
^^^^^
(TODO: Sam: see Parser.parse.consume_oneDec)
```
+ Solution: This PR adds in support for local declarations, along with pretty printing for local declarations in the AST. There's also some tests.
Then, we correctly parse as:
```
λ ~/P/parse-sml on add-local-dec  ./main …
```
> added support for local decs, plus pretty printing

- parse/PrettyPrintAst.sml
+ Problem: I forgot to add in support for pretty printing mutually recursive types (the current code only assumed that there was one). We used to get:
```
λ ~/P/parse-sml on add-datatype-dec ⨯ ./main test/succeed/mutually-recursive-types.sml            00:42:11
type 'a foo = int
and 'b bar = 'b option
and ('c, 'd) baz = 'c * 'd -> int list
type 'a foo = unit -> int bar
and 'a bar = unit -> (string, int array) baz
and ('a, 'b) baz = unit -> int list foo
Parsing...
type 'a foo = int
type 'a foo = unit -> int bar
Parsing succeeded.
```
+ Solution: Added that functionality in. Now it's:
```
λ ~/P/parse-sml on fix-pretty-printing-mutually-recursive-types ⨯ ./main test/succeed/mutually-recursive-types.sml …
```
> fixed pretty printing mutually recursive types

- parse/AstType.sml
- parse/Parser.sml
- parse/PrettyPrintAst.sml
- test/fail/bad-datatypes-1.sml
- test/fail/bad-datatypes-2.sml
- test/succeed/datatypes.sml
+ Problem: We do not currently support datatype declarations
+ Support: This PR adds parsing for datatype declarations, along with pretty printing. We get stuff like: 
```
λ ~/P/parse-sml on add-datatype-dec ⨯ ./main test/succeed/datatypes.sml                          02:55:14
datatype ('a, 'b) either = INL of 'a | INR of 'b
datatype foo = A
datatype even = Z | S1 of odd
and odd = S2 of even
datatype 'a tree = Empty | Node of 'a tree * 'a * 'a tree
datatype ('a, 'b, 'c) complicated =
op Con1 of int * string
| Con2 of int -> string
| Con3
and complicate = op Cons1 | Cons2 of (int, string, bool) complicated
and 'a complex = Const
withtype bar = int
and 'a baz = string
Parsing...
datatype either = INL of 'a | INR of 'b
datatype foo = A
datatype even = Z | S1 of odd
and odd …
```
> added support for datatype declarations

- lex/Token.sml
- parse/AstType.sml
- parse/Parser.sml
- parse/PrettyPrintAst.sml
- test/succeed/specs.sml
Problem: We cannot currently support `eqtype` specifications within a signature. Also, specs is not done.
Solution: Added `eqtype` in, with pretty printing. Also finished off the `spec`s.
> Eqtype specs, refactored ast type, finished specs type

- src/pretty-print/PrettyExpAndDec.sml
I think this commit should finish the remaining step for this issue.
I'm not sure if produces pretty output in all cases. It seems fine so far, based on the examples below:
Input:
```sml
val x =
if b1 then e1
else if b2 then e2
else if b3 then e3
else if b4 then e4
else if b5 then e5
else if b6 then e6
else if b7 then e7
else e8
val y =
if b1 then e1
else if let val y = case z of foo => [1,2,3,4,5,6,8,9,10,11,12] | bar => [1,2,3,4,5,6,8,9,10,11,12] in baz end then e2
else if b3 then e3
else if b4 then e4
else if b5 then e5
else if b6 then e6
else if b7 then e7
else let val y = case z of foo => [1,2,3,4,5,6,8,9,10,11,12] | bar => [1,2,3,4,5,6,8,9,10,11,12] in baz end
```
Output:
```sml
val x =
if b1 then
e1
else if b2 then
e2
else if b3 then
e3
else if b4 then
e4
else if b5 then
e5
else if …
```
> Finishes #29: formatting for if-then-else chaining

- src/base/PrettySimpleDoc.sml
- src/pretty-print/PrettyFun.sml
- src/pretty-print/PrettySig.sml
- src/pretty-print/PrettyStr.sml
- src/pretty-print/PrettyUtil.sml
- src/pretty-print/TokenDoc.sml
Known bugs:
```sml
structure S =
struct
val x = 3
(* hi *)
end
```
- ~~(`include` followed by `sharing` moves `sharing` to `include` line; although, doesn't seem to be due to changes here)~~ moved to #37
> Update module language style

- src/pretty-print/PrettyExpAndDec.sml
> Add rigidity to expression language

- src/pretty-print/PrettyTy.sml
Currently, arrow types naively recurse on the left and right, and result in the following format:
After this update, it will instead do the following:
If you're not crazy about the space before the start of the entire type, then you can remove the `spaces 3` I put on line 67.
> made curried function types nicer

- src/base/PrettyTabbedDoc.sml
- src/prettier-print/PrettierExpAndDec.sml
- src/prettier-print/PrettierFun.sml
- src/prettier-print/PrettierPat.sml
- src/prettier-print/PrettierPrintAst.sml
- src/prettier-print/PrettierSig.sml
- src/prettier-print/PrettierStr.sml
- src/prettier-print/PrettierTy.sml
- src/prettier-print/PrettierUtil.sml
- src/prettier-print/TabbedTokenDoc.sml
Previously we had a primitive `at: tab -> doc`, which we now realize is more aptly named `goto`. This primitive is, frankly, strange to reason about when designing output formats.
This patch removes `at: tab -> doc` and replaces it with `at: tab -> doc -> doc`, where `at t d` places the document `d` beginning at the tab `t`. The precondition (not yet checked automatically) is that `d` should only mention `t` or its descendants; in this way, the formatting of `d` should be context independent, making it easier to reason about resulting layouts. I have a suspicion that this will lead to a more efficient layout algorithm, but that remains to be seen.
> Tabbed doc: declarative `at`

- src/base/DocVar.sml
- src/base/PrettyTabbedDoc.sml
- src/base/sources.mlb
- src/prettier-print/PrettierExpAndDec.sml
- src/prettier-print/TabbedTokenDoc.sml
**(Work-in-progress. Not ready to merge.)**
The goal of this patch is to improve performance by decreasing document "code size". This is motivated by recent updates (88d32c9e6e4ab7f7792e8011d82ff059ab0ceea2 ... 95d285aa5c027103e8caa59d398e244e68152c39) which implemented splittable arguments. The details of splittable arguments don't matter here, but one effect of those changes was that the size of the document generated by the pretty printer increased significantly due to duplication of document descriptions across conditional branches.
The increased document size is very costly: on source code of ~1K lines, `smlfmt` was taking as many as 3-5 minutes to complete.
Here's an example, where we use a "ghost" tab to conditionally place the document `D` either inline or at `otherTab`. This …
> WIP: add doc vars

- src/base/PrettyTabbedDoc.sml
- src/base/Tab.sml
- src/base/sources.mlb
- src/prettier-print/PrettierExpAndDec.sml
- src/prettier-print/PrettierUtil.sml
- src/prettier-print/TabbedTokenDoc.sml
Reuse tabs across `TabbedTokenDoc` and `PrettyTabbedDoc`, allowing for more efficient conversion between the two, and avoiding duplicated code across the two modules.
> Pull out `Tab` structure

- src/ast/AstType.sml
- src/demo.sml
- src/parse-mlb/ParseAllSMLFromMLB.sml
- src/parse/ParseExpAndDec.sml
- src/parse/Parser.sml
- src/prettier-print/PrettierPrintAst.sml
- src/pretty-print/PrettyPrintAst.sml
- src/smlfmt.sml
(Fixes #57.)
Compilers like SML/NJ allow for top-level expressions terminated by a semicolon, e.g.:
```sml
use "foo.sml";
fun bar () = ...
```
This patch implements support for top-level expressions in the parser and pretty printer. By default, top-level expressions are allowed. This can be disabled with the command-line arg `-allow-top-level-exps false`, if desired.
> Allow top level expressions

- src/base/Tab.sml
- src/prettier-print/PrettierExpAndDec.sml
- src/prettier-print/PrettierSig.sml
- src/prettier-print/PrettierUtil.sml
- src/prettier-print/TabbedTokenDoc.sml
- test/fmt/tricky-comments.sml
This fixes an issue with automatic insertion of comments in certain places, for example this output which doesn't look right.
```sml
val _ =
case foo of
(* A *)
Foo => ()
(* B *)
| Bar => ()
```
Here, the automatic insertion of a comment screws up the alignment of the two branches, and the indentation of the comments across the branches is not consistent.
After this patch, it looks much better:
```sml
val _ =
case foo of
(* A *)
Foo => ()
(* B *)
| Bar => ()
```
I created a new tab style (`Tab.Style.allowComments`) which makes the tab work like a "magnet" for comments: any automatically inserted comments are encouraged to move to a nearby magnet. This is implemented by raising comments higher in the document structure, as long the comment doesn't cross a token; see …
> Comment-able tabs

- src/prettier-print/PrettierExpAndDec.sml
Additional uses of splittable expressions, for both `val` declarations and record rows.
OLD OUTPUT
```sml
val hello =
foo (fn () =>
{ foo =
bar baz (1, 2, 3)
, bar =
beez buzz
(3, 2, 1)
})
```
NEW OUTPUT
```sml
val hello = foo (fn () =>
{ foo = bar baz
(1, 2, 3)
, bar = beez buzz
(3, 2, 1)
})
```
> Splittable `val` declarations and record rows

- LICENSE
- src/prettier-print/PrettierExpAndDec.sml
- src/prettier-print/PrettierUtil.sml
- src/prettier-print/TabbedTokenDoc.sml
Trailing comments that start on the same line as the previous token are now associated with that token, which results in better automatic insertion of comments.
INPUT
```sml
val x = a + b (* + c *)
datatype 'a t =
Empty (* nothing here *)
| One of 'a (* only one element *)
(* more than one element is packaged in a sequence *)
| Many of 'a Seq.t
```
OLD OUTPUT
```sml
val x = a + b
(* + c *)
datatype 'a t =
Empty
(* nothing to show *)
| One of 'a
(* only one element *)
(* more than one element is packaged in a sequence *)
| Many of 'a Seq.t
```
NEW OUTPUT
```sml
val x = a + b (* + c *)
datatype 'a t =
Empty (* nothing here *)
| One of 'a (* only one element *)
(* more than one element is packaged in a sequence *)
| Many of 'a Seq.t
```
> Better handling of trailing comments

- src/parse-mlb/ParseAllSMLFromMLB.sml
- src/parse/Parser.sml
- src/prettier-print/TabbedTokenDoc.sml
- src/smlfmt.sml
A couple small fixes for handling comments.
1. Preserve blank lines inside a multi-line comment.
2. Fix edge case: preserve comments in files with only comments and nothing else.
> Comment bugfixes

- README.md
- src/ast/AstType.sml
- src/parse-mlb/ParseAllSMLFromMLB.sml
- src/parse/FixExpPrecedence.sml
- src/parse/ParseExpAndDec.sml
- src/parse/ParseSigExpAndSpec.sml
- src/parse/Parser.sml
- src/parse/ParserUtils.sml
- src/prettier-print/PrettierExpAndDec.sml
- src/prettier-print/PrettierSig.sml
- src/pretty-print/PrettyExpAndDec.sml
- src/pretty-print/PrettySig.sml
- src/pretty-print/PrettyUtil.sml
- src/smlfmt.sml
Progress on #47.
Command-line option `-allow-opt-bar true` enables SuccessorML optional bar syntax, for example:
```sml
signature X =
sig
datatype ('a, 'b) either =
| Left of 'a  (* in first branch of datatype spec *)
| Right of 'b
end
datatype ('a, 'b) either =
| Left of 'a  (* in first branch of datatype declaration *)
| Right of 'b
fun 'a
| foo ([]: 'a list) = 0  (* in first branch of 'fun' declaration *)
| foo (x :: xs) =
case xs of
| [] => 1  (* in first branch of 'case' expression *)
| _ => 1 + foo xs
val bar =
fn
| [] => true  (* in first branch of anonymous function *)
| x :: xs => false
val x =
foo ()
handle
| Subscript => ()  (* in first branch of 'handle' expression *)
| Option => ()
| other => raise other
```
> SuccessorML optional bar syntax

- README.md
- src/ast/AstType.sml
- src/parse-mlb/ParseAllSMLFromMLB.sml
- src/parse/ParseExpAndDec.sml
- src/parse/Parser.sml
- src/prettier-print/PrettierExpAndDec.sml
- src/pretty-print/PrettyExpAndDec.sml
- src/pretty-print/PrettyUtil.sml
- src/smlfmt.sml
Progress on #47.
Command-line option `-allow-record-pun-exps true` enables SuccessorML record punning syntax, for example:
```sml
val x = {foo, bar, baz = beez}
```
> SuccessorML record punning syntax

- README.md
- src/ast/Ast.sml
- src/ast/AstAllows.sml
- src/ast/AstType.sml
- src/parse/ParseExpAndDec.sml
- src/parse/ParseFunNameArgs.sml
- src/parse/ParsePat.sml
- src/prettier-print/PrettierPat.sml
- src/pretty-print/PrettyPat.sml
- src/pretty-print/PrettyUtil.sml
- src/smlfmt.sml
Progress on #47.
Command-line option `-allow-or-pats true` enables SuccessorML record punning syntax, for example:
```sml
val _ = 
(* taken from MLton example: http://mlton.org/SuccessorML *)
case t of
A x | B x | C x => x + 1
| D (x, _) | E (_, x) => x * 2
```
> SuccessorML or-pattern syntax

- src/base/PrettyTabbedDoc.sml
- src/prettier-print/PrettierPrintAst.sml
- src/smlfmt.sml
The pretty printer is technically not linear cost relative to the size of the AST, because of the "splittable expressions" feature I added not too long ago (e.g. in #61).
This has a nasty impact on performance for certain files, and it's somewhat unpredictable -- it depends on how many splittable expressions there are, and also the "depth" of those expressions. If splittable expressions are nested within one another, the cost of the pretty printing algorithm can become exponential.
For example, here's a large input file (approximately 4000 lines) from the MLton repository: [`elaborate-core.fun`](https://github.com/MLton/mlton/blob/master/mlton/elaborate/elaborate-core.fun). On this file, `smlfmt` was taking 12 seconds to complete using 4.3 GB of memory (wow!)
At first, I considered fixing …
> performance improvement: delayed `newTab` and `newTabWithStyle` to avoid unnecessary work

- src/parse-mlb/ParseAllSMLFromMLB.sml
- src/parse-mlb/ParseAnnotations.sml
- src/parse-mlb/sources.mlb
MLB files allow for controlling SuccessorML language features, for example:
```
ann
"allowOrPats true"
in
foo.sml
end
```
Previously these were ignored. Now, we handle the following annotations:
* `allowOrPats [true|false]`
* `allowRecordPunExps [true|false]`
* `allowOptBar [true|false]`
These are the current set of SuccessorML features that `smlfmt` supports. As additional SuccessorML features are added, we will extend the supported MLB annotations as well.
Note that default settings can still be controlled with `smlfmt` command-line options, for example `-allow-opt-bar true`. These default settings will be overridden by annotations within an MLB, similar to the behavior of MLton's `-default-ann ...`.
> handle annotations in MLB `ann ... in ... end`

- README.md
- src/ast/sources.mlb
- src/base/AstAllows.sml
- src/base/sources.mlb
- src/lex-mlb/MLBLexer.sml
- src/lex/Lexer.sml
- src/parse-mlb/ParseAnnotations.sml
- src/parse/Parser.sml
- src/smlfmt.sml
- src/syntax-highlighting/SyntaxHighlighter.sml
- test/succeed/extended-text.mlb
- test/succeed/successor-ml/extended-text.sml
Fixes #49 and additional progress on #47.
Command-line option `-allow-extended-text-consts true` allows for UTF-8 bytes within strings, for example:
```sml
val a = "🍰"
val x = print "🂡\n"
```
This can also be controlled from within an MLB following MLton conventions:
```
ann "allowExtendedTextConsts true" in
foo.sml
end
```
Note that this feature does not check for validity of a UTF-8 byte sequence. We could add that later, if desired.
> SuccessorML extended text constants

- README.md
- src/smlfmt.sml
In the case where an incompatible flag is not set, `--stdio` will now be implied when standard input is not a terminal. This enables uses like
```bash
smlfmt < IN > OUT
```
without needing an additional flag.
The flag is currently left in, but I don't think it is necessary since users can simply do `cat | smlfmt` or similar if they'd really like to type over stdin at the terminal.
This isn't currently a breaking change since `--stdio` hasn't been included in a release yet, either any option (e.g., the one implemented here, or removing the explicit `--stdio` flag entirely) maintains backwards compatibility.
Another option would be to let `-` have specific meaning as an input file, designating stdin, which is common in Unix utilities, although this would presumably be a breaking change …
> feat: Make `--stdio` the default for non-tty stdin

- README.md
- src/smlfmt.sml
Standard input and output are used if no files are given and standard input is not connected to the terminal.
Closes #85
> Remove --stdio flag

- src/smlfmt.sml
This PR adds in a `--read-only` flag, which causes `smlfmt` to skip interactive confirmation in the negative sense, only parsing all files without previewing or formatting them. It's called `read-only`, because it just causes the files to be parsed/read, without overwriting or formatting.
I'm interested in using `smlfmt` to detect syntax errors in code. I don't need the preview, since I just want the error output, so `--preview-only` isn't what I want.
Just added a command-line flag.
This is what the flag does on my machine:
> feat(cli): add `read-only` flag

- Makefile
Actually, the real reason for this PR is to ask for a new release.  The stdin behaviour added in April is really useful for editor integration.
> Add "make install" target.

- src/Main.smlnj.sml
- src/smlfmt.sml
- test/runall
This is a follow-up PR for #91.
About the flag name, what do you think of `--dryrun`?
> Add flag to check if files are formatted

- Makefile
Packaging tools expect makefiles to respect `DESTDIR`
> fix install target

- Makefile
- README.md
- src/ast/AstType.sml
- src/ast/CompareAst.sml
- src/base/AstAllows.sml
- src/lex-mlb/MLBLexer.sml
- src/parse-mlb/ParseAnnotations.sml
- src/parse/ParseExpAndDec.sml
- src/parse/ParseSigExpAndSpec.sml
- src/prettier-print/PrettierExpAndDec.sml
- src/prettier-print/PrettierSig.sml
- src/pretty-print/PrettySig.sml
- src/pretty-print/PrettyUtil.sml
- src/smlfmt.sml
- src/syntax-highlighting/SyntaxHighlighter.sml
- test/succeed/sig-withtype.mlb
- test/succeed/successor-ml/sig-withtype.sml
Also add an option to enable all SuccessorML features. See the commit messages for more details.
> Add support for SuccessorML withtype in signatures syntax
